[package]
name = "map"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_matches = "1.5"
rand = { version = "0.8.5", default-features = false, features = ["alloc"] }
rand_xorshift = "0.3.0"
# rand = "0.8.0"
# rand_xorshift = "0.3.0"