[package]
name = "mio-tcpserver"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = { version = "0.9.3", default-features = false }
mio = { git = "https://github.com/minminm/mio.git", branch = "ruxos", features = ["os-poll", "net"] }

# Only for selection of std features
# axstd = { path = "../../../ulib/axstd", features = ["net"], optional = true }
